### create new user
POST  http://localhost:8000/api/v1/Clientuser
Content-Type:  application/json
   
{
  "fName":"sanish",
  "lName":"khadka",
    "email":"rickeykhd@gmail.com",
    "password": "123456",
    "role":"user"
}
### login user
POST http://localhost:8000/api/v1/Clientlogin
Content-Type:  application/json
   
{
     "email":"sanishkhadka1@gmail.com",
    "password": "123456"
}


### product display 
GET  http://localhost:8000/api/v1/productdisplay


### product display 
GET  http://localhost:8000/api/v1/Categoryproductdisplay/60a312210bf0e52780a3ec9b

### productslug display 
GET  http://localhost:8000/api/v1/slug/apple

### product display 
GET  http://localhost:8000/api/v1/Category

