### create new user
POST  http://localhost:8000/api/v1/Clientuser
Content-Type:  application/json
   
{
  "fName":"sanish",
  "lName":"khadka",
    "email":"amrit@gmail.com",
    "password": "123456",
    "role":"user"
}
### login user
POST http://localhost:8000/api/v1/Clientlogin
Content-Type:  application/json
   
{
     "email":"rickeykhd@gmail.com",
    "password": "123456"
}

### logout user
POST http://localhost:8000/api/v1/LogOut
Content-Type:  application/json
   
{
     "_id":"60a261e7a8a1ac189ceba1f2"
   
}
### display userprofile
POST  http://localhost:8000/api/v1/token
Authorization: eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJpY2tleWtoZEBnbWFpbC5jb20iLCJpYXQiOjE2MjM2NjkwOTksImV4cCI6MTYyNTM5NzA5OX0.YHAAqmwmzfckixiDa9SWSJRyprfb2B8Z2R-hGdCd-8A

### product display 
GET  http://localhost:8000/api/v1/productdisplay


### product display 
GET  http://localhost:8000/api/v1/Categoryproductdisplay/60b5baf2c1752a37cc2e00fa

### productslug display 
GET  http://localhost:8000/api/v1/slug/apple

### product display 


GET  http://localhost:8000/api/v1/Category

